marks=[]

f1=int(input("Enter a marks: "))
marks.append(f1)
f2=int(input("Enter another marks: "))
marks.append(f2)   
f3=int(input("Enter one more marks: "))
marks.append(f3)
f4=int(input("Enter the last marks: "))
marks.append(f4)
f5=int(input("Enter one more marks: "))
marks.append(f5)
f6=int(input("Enter the last marks: "))
marks.append(f6)
marks.sort() 
print(marks)